sudo: required
language: python
python:
  - "3.7"

services:
  - mysql

dist: xenial

before_install:
  - mysql_upgrade --force
  - sudo service mysql restart

install:
  - pip3 install -e .
  - pip3 install -r requirements.txt

script:
  # ================ Functional tests =============== #
  - py.test --cov=src

  # ================ Static Analysis ================= #
  - pylint src

after_success:
  - coveralls